#### Task 13 result

In [2]:
import numpy as np


1. Creating a 6x6 Numpy array with random integers between 1 and 50. Display the array

In [4]:
arr = np.random.randint(1, 51, size=(6, 6))
print(arr)

[[43 21 21 36  4 11]
 [37 11 12 49  2  2]
 [33 18 18 29 43 41]
 [15 13 25 23 26  3]
 [18  1 23 17 32 18]
 [ 8 10 13 21 37 18]]


2. Extract the following from the array you created in Question 1: The first two rows. The last three columns. All even numbers in the array.

In [7]:
# The first two row
print("First two row\n", arr[:2])

# The last three column
print("Last three column\n", arr[:, -3:])

# All even number
even_arr = arr[arr % 2 == 0]
print("All even\n", even_arr)

First two row
 [[43 21 21 36  4 11]
 [37 11 12 49  2  2]]
Last three column
 [[36  4 11]
 [49  2  2]
 [29 43 41]
 [23 26  3]
 [17 32 18]
 [21 37 18]]
All even
 [36  4 12  2  2 18 18 26 18 32 18  8 10 18]


3. Perform the following array transformations: Reshape the array into a 3D (3, 2, 6) array. Flatten the reshaped array back to 1D.

In [9]:
reshape_3D = arr.reshape(3, 2, 6)
print("Reshape array to 3D\n", reshape_3D)
flatten_arr = reshape_3D.flatten()
print("flatten back to 1D\n", flatten_arr)

Reshape array to 3D
 [[[43 21 21 36  4 11]
  [37 11 12 49  2  2]]

 [[33 18 18 29 43 41]
  [15 13 25 23 26  3]]

 [[18  1 23 17 32 18]
  [ 8 10 13 21 37 18]]]
flatten back to 1D
 [43 21 21 36  4 11 37 11 12 49  2  2 33 18 18 29 43 41 15 13 25 23 26  3
 18  1 23 17 32 18  8 10 13 21 37 18]


4. Generate a 4x4 identity matrix and replace the diagonal with numbers from 10 to 40, with a step of 10.

In [ ]:
# 4 x 4 identity matrix
identity_matrix = np.eye(4)
print("Identity matrix:\n", identity_matrix)

# Replcaing the diagonal with number
np.fill_diagonal(identity_matrix, [10, 20, 30, 40])
print("Diagonal matrix\n", identity_matrix)

5. Perform matrix multiplication between: A 3x4 matrix of random integers (1-10) A 4x3 matrix of random integers (1-10)

In [ ]:
a_arr = np.random.randint(1, 11, size=(3, 4))
b_arr = np.random.randint(1, 11, size=(4, 3))

# Array product
# product_arr = np.dot(a_arr, b_arr)
# product_arr
product_arr = a_arr @ b_arr
print("Array product\n", product_arr)

6. Create a function that takes a 2D NumPy array as input and returns a new array where: All even numbers are squared. All odd numbers are replaced by -1.

In [ ]:
def arr_even_sq_odd_minus_1(arr):
    return np.where(arr % 2 == 0, arr **2, -1)

arr = np.random.randint(1, 20, size=(3, 4))
arr_opration = arr_even_sq_odd_minus_1(arr)

print("Array before operation\n", arr)
print("Array after operation\n", arr_opration)