#### Task 13 result

In [2]:
import numpy as np


1. Creating a 6x6 Numpy array with random integers between 1 and 50. Display the array

In [3]:
arr = np.random.randint(1, 51, size=(6, 6))
print(arr)

[[47 37 33 47 35  8]
 [42 46 20 18  1 24]
 [47 24 14 26 13  2]
 [16 47 31  8 18 21]
 [10  9 31 15 11 22]
 [45 45  6 35 13 19]]


2. Extract the following from the array you created in Question 1: The first two rows. The last three columns. All even numbers in the array.

In [4]:
# The first two row
print("First two row\n", arr[:2])

# The last three column
print("Last three column\n", arr[:, -3:])

# All even number
even_arr = arr[arr % 2 == 0]
print("All even\n", even_arr)

First two row
 [[47 37 33 47 35  8]
 [42 46 20 18  1 24]]
Last three column
 [[47 35  8]
 [18  1 24]
 [26 13  2]
 [ 8 18 21]
 [15 11 22]
 [35 13 19]]
All even
 [ 8 42 46 20 18 24 24 14 26  2 16  8 18 10 22  6]


3. Perform the following array transformations: Reshape the array into a 3D (3, 2, 6) array. Flatten the reshaped array back to 1D.

In [5]:
reshape_3D = arr.reshape(3, 2, 6)
print("Reshape array to 3D\n", reshape_3D)
flatten_arr = reshape_3D.flatten()
print("flatten back to 1D\n", flatten_arr)

Reshape array to 3D
 [[[47 37 33 47 35  8]
  [42 46 20 18  1 24]]

 [[47 24 14 26 13  2]
  [16 47 31  8 18 21]]

 [[10  9 31 15 11 22]
  [45 45  6 35 13 19]]]
flatten back to 1D
 [47 37 33 47 35  8 42 46 20 18  1 24 47 24 14 26 13  2 16 47 31  8 18 21
 10  9 31 15 11 22 45 45  6 35 13 19]


4. Generate a 4x4 identity matrix and replace the diagonal with numbers from 10 to 40, with a step of 10.

In [6]:
# 4 x 4 identity matrix
identity_matrix = np.eye(4)
print("Identity matrix:\n", identity_matrix)

# Replcaing the diagonal with number
np.fill_diagonal(identity_matrix, [10, 20, 30, 40])
print("Diagonal matrix\n", identity_matrix)

Identity matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Diagonal matrix
 [[10.  0.  0.  0.]
 [ 0. 20.  0.  0.]
 [ 0.  0. 30.  0.]
 [ 0.  0.  0. 40.]]


5. Perform matrix multiplication between: A 3x4 matrix of random integers (1-10) A 4x3 matrix of random integers (1-10)

In [7]:
a_arr = np.random.randint(1, 11, size=(3, 4))
b_arr = np.random.randint(1, 11, size=(4, 3))

# Array product
# product_arr = np.dot(a_arr, b_arr)
# product_arr
product_arr = a_arr @ b_arr
print("Array product\n", product_arr)

Array product
 [[120 106  97]
 [208 159 200]
 [163 100 130]]


6. Create a function that takes a 2D NumPy array as input and returns a new array where: All even numbers are squared. All odd numbers are replaced by -1.

In [8]:
def arr_even_sq_odd_minus_1(arr):
    return np.where(arr % 2 == 0, arr **2, -1)

arr = np.random.randint(1, 20, size=(3, 4))
arr_opration = arr_even_sq_odd_minus_1(arr)

print("Array before operation\n", arr)
print("Array after operation\n", arr_opration)

Array before operation
 [[18  6  2  9]
 [ 7 12  4 12]
 [10 10 16  1]]
Array after operation
 [[324  36   4  -1]
 [ -1 144  16 144]
 [100 100 256  -1]]
