In [13]:
import numpy as np

1. Create a new 5x4 matrix of scores (5 students, 4 subjects). Compute each student's total score and the average per subject

In [14]:
students = np.array([[80, 70, 90, 60],
                     [60, 85, 75, 70],
                     [95, 88, 92, 80],
                     [70, 60, 65, 75],
                     [55, 70, 75, 80]])

students_total_score = np.sum(students, axis=1)
print(f"Student total score:\n{students_total_score}")

students_avg_score = np.average(students, axis=0)
print("\nAverage per subject:\n", students_avg_score)

Student total score:
[300 290 355 270 280]

Average per subject:
 [72.  74.6 79.4 73. ]


2. Suppose one subject(e.g., science) is times more important than others. Apply scalar multiplication and recompute totals 

In [15]:
# getting the science score
science_score = students[:, 2].copy()
# multiplying science score by 3
science_score *= 3

students[:, 2] = science_score
print("New student score:\n", students)

new_total_score = np.sum(students, axis=1)
print("\nNew total score:")
new_total_score

New student score:
 [[ 80  70 270  60]
 [ 60  85 225  70]
 [ 95  88 276  80]
 [ 70  60 195  75]
 [ 55  70 225  80]]

New total score:


array([480, 440, 539, 400, 430])

3. Define new weight for grading(e.g 40%, 20%, 30%, 10%). compute final grades using matrix multiplication. using  

In [18]:
weight = np.array([0.4, 0.2, 0.3, 0.1])

grade = students @ weight
grade

array([133. , 115.5, 146.4, 106. , 111.5])